@startuml SetVariable Flow
participant UEFI
participant VariableSmm
participant SPI
participant RPMC

  opt If Write-NOT-Init-ed
    VariableSmm -> SPI : UpdateState(OldMetaDataHmacVar, IN_DELETE)
    VariableSmm -> RPMC : RequestMonotonicCounter()
    RPMC --> VariableSmm : Counter
    VariableSmm -> VariableSmm : HMAC(Key, Var1||..||VarN||Counter+1)
    VariableSmm -> SPI : AddVariable(NewMetaDataHmacVar, ADDED)
    VariableSmm -> RPMC : IncrementMonotonicCounter()
    VariableSmm -> SPI : UpdateState(OldMetaDataHmacVar, DELETED)
  end

  UEFI -> VariableSmm ++ : SetVariable(VarData)

  VariableSmm -> SPI : UpdateState(OldMetaDataHmacVar,**IN_DELETE**)
  note right of VariableSmm : A

  opt If Encryption-Enabled
    VariableSmm -> VariableSmm : EncryptVariable(**VarData**)
  end

  VariableSmm -> RPMC : RequestMonotonicCounter()
  RPMC --> VariableSmm : Counter

  activate VariableSmm
  VariableSmm -> VariableSmm : HMAC(Key, Var1||..||VarN||**VarData**||**Counter+1**)
  VariableSmm -> SPI ++ : AddVariable(NewMetaDataHmacVar,**ADDED**)
  note right of VariableSmm : B
  return
  deactivate VariableSmm

  VariableSmm -> SPI ++ : AddVariable(VarData,**ADDED**)
  note right of VariableSmm : C
  return

  VariableSmm -> RPMC ++ : **IncrementMonotonicCounter()**
  note right of VariableSmm : D
  return

  VariableSmm -> SPI : UpdateState(OldMetaDataHmacVar,**DELETED**)
  note right of VariableSmm : E

  return EFI_SUCCESS
@enduml
